apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spiffe-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-demo-app
  template:
    metadata:
      labels:
        app: spiffe-demo-app
    spec:
      containers:
      - name: spiffe-demo-app
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: "unix:///spiffe-workload-api/spire-agent.sock"
        ports:
        - containerPort: 8080