apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: spiffe-demo-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  {{if .Values.service.type}}
  type: {{ .Values.service.type }}
  {{end}}